"""Update Song model with new attributes

Revision ID: ba5da4830e16
Revises: 
Create Date: 2024-08-24 00:16:53.022178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba5da4830e16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('emotion', sa.Enum('ANGRY_NORMAL', 'ANGRY_INTENSE', 'SAD_NORMAL', 'SAD_INTENSE', name='emotion'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('artist', sa.String(length=100), nullable=False),
    sa.Column('album', sa.String(length=100), nullable=False),
    sa.Column('spotify_id', sa.String(length=22), nullable=False),
    sa.Column('emotion', sa.Enum('ANGRY_NORMAL', 'ANGRY_INTENSE', 'SAD_NORMAL', 'SAD_INTENSE', name='emotion'), nullable=False),
    sa.Column('danceability', sa.Float(), nullable=False),
    sa.Column('energy', sa.Float(), nullable=False),
    sa.Column('key', sa.String(length=10), nullable=False),
    sa.Column('loudness', sa.Float(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('speechiness', sa.Float(), nullable=False),
    sa.Column('acousticness', sa.Float(), nullable=False),
    sa.Column('instrumentalness', sa.Float(), nullable=False),
    sa.Column('liveness', sa.Float(), nullable=False),
    sa.Column('valence', sa.Float(), nullable=False),
    sa.Column('tempo', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('popularity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spotify_id')
    )
    op.create_table('playlist_songs',
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ),
    sa.PrimaryKeyConstraint('playlist_id', 'song_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist_songs')
    op.drop_table('song')
    op.drop_table('playlist')
    # ### end Alembic commands ###
